### ISSUE TITLE
version.php - $module used instead of $plugin

### ISSUE THREAD

**Issue by bretin** [OohooDevTeam/moodle-format_tabtopics#2]
In the file version.php, the lines

```
$module->maturity = MATURITY_STABLE;
$module->release = '2.0.0 (Build: 2012081500)';
```

generate errors in the plugin installation.

Use `$plugin` instead of `$module`.

**Comment by jongeriu** [comment]
Fixed when redesigned plugin off of moodle 2.3.1's core "topics".  bb586378059866d3eef2a83166e3d161a6d9e3e8
