### ISSUE TITLE
Course display

### ISSUE THREAD

**Issue by bretin** [OohooDevTeam/moodle-format_tabtopics#3]
Only Moodle 2.3: 
On the course display with a tabtopic format, a fatal error displays:
`Fatal error: Call to undefined function course_get_display() in ...\moodle\course\format\tabtopic\format.php on line 354`
Apparently, the functions `course_get_display()`, `course_set_display` and the `course_display` table has been deleted in Moodle 2.3.

**Comment by jongeriu** [comment]
Fixed when redesigned plugin off of moodle 2.3.1's core "topics". bb586378059866d3eef2a83166e3d161a6d9e3e8
