### ISSUE TITLE
Git does not show moodle.org version

### ISSUE THREAD

**Issue by actXc** [OohooDevTeam/moodle-format_tabtopics#6]
Thanks for maintaining the plugin.
we are using GIT to maintain our system and do updates.
Are you planning to update GIT to the newest version, like in moodle database?

**Comment by actXc** [comment]
sorry - wrong click- not closed

**Comment by bretin** [comment]
Hi Guido,

Yes we plan on updating the plugin for Moodle 2.7 and up.
The past few months were a bit crazy for us so we didn't had time to update our plugins for Moodle 2.7.
We'll try to do it soon!

Thanks,

Nicolas

**Comment by actXc** [comment]
I thought you pull the zip for moodle database  from here

**Comment by bretin** [comment]
Oh sorry I read a bit too fast your email.
Yes, every update published on Moodle is pushed on Github at the same
moment.

In the process, we make the update, commit on Github and  then make a zip
file that we publish on Moodle.

Thanks,

Nicolas

**Comment by actXc** [comment]
Now I found this line:

"Repository closed - Please see https://github.com/oohoo/moodle-format_tabtopics for the more recent version"

and it seems to be the right version!
